# Ultralytics 🚀 AGPL-3.0 License - https://ultralytics.com/license

# 在 Docker Hub 上构建 ultralytics/ultralytics:latest-cpu 镜像：https://hub.docker.com/r/ultralytics/ultralytics
# 适用于推理的轻量级 CPU 镜像（基于 latest-python 扩展）

# 基于 Ultralytics Python 镜像构建
FROM ultralytics/ultralytics:latest-python

# 将默认命令设置为 bash
CMD ["/bin/bash"]

# Usage --------------------------------------------------------------------------------------------------------------

# Production builds: https://github.com/ultralytics/ultralytics/blob/main/.github/workflows/docker.yml
# Example (build): t=ultralytics/ultralytics:latest-cpu && docker build -f docker/Dockerfile-cpu -t $t .
# Example (push): docker push $t
# Example (pull): t=ultralytics/ultralytics:latest-cpu && docker pull $t
# Example (run): docker run -it --ipc=host $t
# Example (run-with-volume): docker run -it --ipc=host -v "$PWD/shared/datasets:/datasets" $t
