# Ultralytics 🚀 AGPL-3.0 License - https://ultralytics.com/license

# 在 Docker Hub 上构建 ultralytics/ultralytics:latest-python 镜像：https://hub.docker.com/r/ultralytics/ultralytics
# 针对 YOLO 推理优化的轻量级 CPU 镜像

FROM python:3.13-slim-trixie

# 设置环境变量（禁止 PyTorch NNPACK 警告）
ENV PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1 \
    PIP_NO_CACHE_DIR=1 \
    PIP_BREAK_SYSTEM_PACKAGES=1 \
    UV_BREAK_SYSTEM_PACKAGES=1 \
    TORCH_CPP_LOG_LEVEL=ERROR

# 下载到用户配置目录
ADD https://github.com/ultralytics/assets/releases/download/v0.0.0/Arial.ttf \
    https://github.com/ultralytics/assets/releases/download/v0.0.0/Arial.Unicode.ttf \
    /root/.config/Ultralytics/

# 安装 Linux 软件包
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    python3-pip git zip unzip wget curl htop libgl1 libglib2.0-0 && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# 创建工作目录
WORKDIR /ultralytics

# 复制内容并配置依赖项
COPY . .
RUN sed -i'' -e 's/"opencv-python/"opencv-python-headless/' pyproject.toml
ADD https://github.com/ultralytics/assets/releases/download/v8.4.0/yolo26n.pt .

# 安装 pip 软件包
RUN pip install uv && \
    uv pip install --system --no-cache -e . \
    --extra-index-url https://download.pytorch.org/whl/cpu \
    --index-strategy unsafe-best-match && \
    rm -rf tmp ~/.cache /root/.config/Ultralytics/persistent_cache.json

# Usage --------------------------------------------------------------------------------------------------------------

# Production builds: https://github.com/ultralytics/ultralytics/blob/main/.github/workflows/docker.yml
# Example (build): t=ultralytics/ultralytics:latest-python && docker build -f docker/Dockerfile-python -t $t .
# Example (push): docker push $t
# Example (pull): t=ultralytics/ultralytics:latest-python && docker pull $t
# Example (run): docker run -it --ipc=host $t
# Example (run-with-volume): docker run -it --ipc=host -v "$PWD/shared/datasets:/datasets" $t
