# Ultralytics 🚀 AGPL-3.0 License - https://ultralytics.com/license

# 构建用于部署到 Docker Hub 的 GitHub Actions CI runner 镜像：https://hub.docker.com/r/ultralytics/ultralytics
# 此镜像针对 YOLO 推理和纯 CPU 测试进行了 CPU 优化

# 基于 Ultralytics CPU 镜像启动
FROM ultralytics/ultralytics:latest-cpu
COPY --from=node:24-bookworm-slim /usr/local/bin/node /usr/local/bin/node
COPY --from=node:24-bookworm-slim /usr/local/lib/node_modules/npm/ /usr/local/lib/node_modules/npm/

# 为 runner 设置额外环境变量（版本号不带 "v"）
ARG RUNNER_VERSION=2.334.0
ENV RUNNER_ALLOW_RUNASROOT=1 \
    DEBIAN_FRONTEND=noninteractive

# 设置工作目录
WORKDIR /actions-runner

# 从 https://github.com/actions/runner 下载并解压 runner，然后安装依赖项
RUN FILENAME=actions-runner-linux-x64-${RUNNER_VERSION}.tar.gz && \
    ln -s ../lib/node_modules/npm/bin/npm-cli.js /usr/local/bin/npm && \
    ln -s ../lib/node_modules/npm/bin/npx-cli.js /usr/local/bin/npx && \
    curl -fLso "$FILENAME" "https://github.com/actions/runner/releases/download/v${RUNNER_VERSION}/${FILENAME}" && \
    tar xzf "$FILENAME" && \
    rm "$FILENAME" && \
    # 安装 runner 依赖项 \
    uv pip install --system pytest-cov && \
    ./bin/installdependencies.sh && \
    apt-get install -y --no-install-recommends gpg libicu-dev sudo && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# 使用 JSON ENTRYPOINT 命令，以默认 TOKEN 和 NAME 配置并启动 runner
ENTRYPOINT ["sh", "-c", "./config.sh --url https://github.com/ultralytics --token ${GITHUB_RUNNER_TOKEN:-TOKEN} --name ${GITHUB_RUNNER_NAME:-NAME} --labels cpu-latest --replace && exec ./run.sh"]

# Usage --------------------------------------------------------------------------------------------------------------

# Production builds: https://github.com/ultralytics/ultralytics/blob/main/.github/workflows/docker.yml
# Example (build): t=ultralytics/ultralytics:latest-runner-cpu && docker build -f docker/Dockerfile-runner-cpu -t $t .
# Example (push): docker push $t
# Example (pull): t=ultralytics/ultralytics:latest-runner-cpu && docker pull $t
# Example (run): docker run -d --restart unless-stopped -e GITHUB_RUNNER_TOKEN=TOKEN -e GITHUB_RUNNER_NAME=NAME --ipc=host $t
