# Ultralytics 🚀 AGPL-3.0 License - https://ultralytics.com/license

# 在 Docker Hub 上构建 ultralytics/ultralytics:latest-jetson-jetpack5 镜像：https://hub.docker.com/r/ultralytics/ultralytics
# 支持在 Jetson Xavier NX、AGX Xavier、AGX Orin、Orin Nano 和 Orin NX 的 JetPack5.1.2 上运行 YOLO

# Start FROM https://catalog.ngc.nvidia.com/orgs/nvidia/containers/l4t-jetpack
FROM nvcr.io/nvidia/l4t-jetpack:r35.4.1

# 设置环境变量
ENV PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1 \
    PIP_NO_CACHE_DIR=1 \
    PIP_BREAK_SYSTEM_PACKAGES=1 \
    UV_BREAK_SYSTEM_PACKAGES=1

# 下载到用户配置目录
ADD https://github.com/ultralytics/assets/releases/download/v0.0.0/Arial.ttf \
    https://github.com/ultralytics/assets/releases/download/v0.0.0/Arial.Unicode.ttf \
    /root/.config/Ultralytics/

# 安装依赖项
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    git python3-pip libopenmpi-dev libopenblas-base libomp-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# 创建工作目录
WORKDIR /ultralytics

# 复制内容并配置依赖项
COPY . .
RUN sed -i'' -e 's/"opencv-python/"opencv-python-headless/' pyproject.toml
ADD https://github.com/ultralytics/assets/releases/download/v8.4.0/yolo26n.pt .

# 将 pyproject.toml 中的 TF.js 版本替换为 'tensorflowjs>=3.9.0'，以兼容 JetPack5 并安装软件包
RUN sed -i 's/^\( *"tensorflowjs\)>=.*\(".*\)/\1>=3.9.0\2/' pyproject.toml && \
    python3 -m pip install --upgrade pip uv

# 使用 pip 安装 onnxruntime-gpu、torch、torchvision 和 ultralytics，然后删除构建文件
RUN uv pip install --system \
    https://github.com/ultralytics/assets/releases/download/v0.0.0/onnxruntime_gpu-1.16.3-cp38-cp38-linux_aarch64.whl \
    https://github.com/ultralytics/assets/releases/download/v0.0.0/torch-2.1.0a0+41361538.nv23.06-cp38-cp38-linux_aarch64.whl \
    https://github.com/ultralytics/assets/releases/download/v0.0.0/torchvision-0.16.2+c6f3977-cp38-cp38-linux_aarch64.whl && \
    # TensorRT 导出需要较低版本的 'numpy'
    uv pip install --system numpy==1.23.5 && \
    uv pip install --system -e ".[export]" && \
    # 删除多余的构建文件
    rm -rf *.whl /root/.config/Ultralytics/persistent_cache.json

# Usage --------------------------------------------------------------------------------------------------------------

# Production builds: https://github.com/ultralytics/ultralytics/blob/main/.github/workflows/docker.yml
# Example (build): t=ultralytics/ultralytics:latest-jetson-jetpack5 && docker build --platform linux/arm64 -f docker/Dockerfile-jetson-jetpack5 -t $t .
# Example (push): docker push $t
# Example (pull): t=ultralytics/ultralytics:latest-jetson-jetpack5 && docker pull $t
# Example (run-jetson): docker run -it --ipc=host --runtime=nvidia $t
# Example (run-jetson-with-volume): docker run -it --ipc=host --runtime=nvidia -v "$PWD/shared/datasets:/datasets" $t
